### ISSUE TITLE
Resource xSmbShare was not found

### ISSUE THREAD

**Issue by kylebevans** [PowerShell/xSmbShare#16]
We used to use this resource without any problems, and suddenly it has started failing across all of our Windows 2012R2 Servers.  Here is the output:

PS C:\Windows\system32> $PSVersionTable.PSVersion

Major  Minor  Build  Revision

---

5      0      10586  117     

PS C:\Windows\system32> get-dscresource xSmbShare

ImplementedAs   Name                      ModuleName                     Version    Properties                                        

---

PowerShell      xSmbShare                 xSmbShare                      2.0.0.0    {Name, Path, ChangeAccess, ConcurrentUserLimit...}
PowerShell      xSmbShare                 xSmbShare                      1.1.0.0    {Name, Path, ChangeAccess, ConcurrentUserLimit...}

PS C:\Windows\system32> Invoke-DscResource -Method test -Name xSmbShare -Property @{Name='apps$';Description='apps folder share';Ensure='Present';Path='E:\';FolderEnumerationMode='AccessBased';FullAccess=@('Everyone')} -Verbose -ModuleName xSmbShare
Invoke-DscResource : Resource xSmbShare was not found.
At line:1 char:1
- Invoke-DscResource -Method test -Name xSmbShare -Property @{Name='app ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Invoke-DscResource], ArgumentException
  - FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.DesiredStateConfiguration.Commands.InvokeDscResourceMethodCommand

**Comment by kwirkykat** [comment]
@kev111 Try calling `Remove-Module xSmbShare`. This should remove both versions from the list of imported modules (which you can see by calling `Get-Module`). Then when you run the configuration again, it should only import the new version.

**Comment by kylebevans** [comment]
Hi Katie,

That didn't work, but uninstalling all versions and then installing the latest again worked.  Thanks.

**Comment by kwirkykat** [comment]
This is actually an issue with DSC/PowerShell and not with this specific module. Closing this issue as external to this module.
