### ISSUE TITLE
Unable to Add Domain User/Computer

### ISSUE THREAD

**Issue by hisingh2017** [PowerShell/xSmbShare#19]
I am using xSMBSHARE via dsc resource in chef recipe and able to enable share for local users but not able to share folder for any AD user/computer. 

Below code i am trying  : 

Chef Recipe  : 

dsc_resource 'enable_file_share' do
  resource :xSmbShare
  property :name, 'QUORUM'
  property :Path, 'D:\QUORUM'
  property :FullAccess, ['domain_name\domain_Computer']
  property :Description, "description goes here for this share"
  property :PsDscRunAsCredential, ps_credential('domain_name\domain_user', 'XXXX')
end

After i ran chef recipe on Target Server, got the below error:

Running handlers:
[2017-11-07T10:05:08+00:00] ERROR: Running exception handlers
Running handlers complete
[2017-11-07T10:05:08+00:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 12 seconds
[2017-11-07T10:05:08+00:00] FATAL: Stacktrace dumped to c:/chef/cache/chef-stacktrace.out
[2017-11-07T10:05:08+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-11-07T10:05:08+00:00] FATAL: Chef::Exceptions::PowershellCmdletException: dsc_resource[enable_file_share] (dsc_coo
kbook::enable_file_share line 12) had an error: Chef::Exceptions::PowershellCmdletException: Powershell Cmdlet failed: N
o mapping between account names and security IDs was done.
    + CategoryInfo          : NotSpecified: (MSFT_SMBShare:) [], CimException
    + FullyQualifiedErrorId : Windows System Error 1332,New-SmbShare
    + PSComputerName        : localhost

The PowerShell DSC resource '[xSmbShare]DirectResourceAccess' with SourceInfo '' threw one or more non-terminating
errors while running the Set-TargetResource functionality. These errors are logged to the ETW channel called
Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost

Please Help!

**Comment by arri-cc** [comment]
I ran into this same issue a few days ago.  I’m looking into it.

**Comment by johlju** [comment]
@hisingh2017 @arri-cc did you find out more information about this problem?

**Comment by arri-cc** [comment]
I still need to test this scenario against underlying cmdlets
