### ISSUE TITLE
Request - Should be able to pass empty strings to all but one Access Parameter. 

### ISSUE THREAD

**Issue by DavidLean** [PowerShell/xSmbShare#21]
When creating a share, currently it throws an error if an empty string is passed to ANY of the following permissions parameters; FullAccess, ChangeAccess, ReadAccess, NoAccess 

> Cannot validate argument on parameter 'FullAccess'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
    + CategoryInfo          : InvalidData: (:) [], CimException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,New-SmbShare
    + PSComputerName        : EDWDEV3-RPT

It would be much better if the error was only thrown if ALL permission parameters were unspecified.  
This would make it much easier to pass a hashtable to set a lot of shares at the same time. 
Not every type of permission would need to be specified for every share. Currently it is a challenge to dynamically drop parameters if the value you are passing is empty.
Example

```
foreach($Share in $Node.Shares) {
        $ShareName = 'ShareFolder' + $Share.Name
	xSmbShare $ShareName
	{
		DependsOn     = $FolderDependsOn
		Ensure        = 'Present'
		Name          = $Share.Name
		Path          = $Share.Path
		FullAccess    = $Share.FullAccess  
		ChangeAccess  = $Share.ChangeAccess
		ReadAccess    = $Share.ReadAccess
		NoAccess      = $Share.DenyAccess' 
	}
}
```

Permitting a PSD1 to contain the values

```
Shares = @(
	@{ 
		Name = 'ARCHIVE'
	        Path = 'E:\ARCHIVE'
		FullAccess = 'EDW_Admins'
		ChangeAccess = 'AZ\60061671'
		ReadAccess = 'Everyone' 
	},
	@{ 
		Name = 'DROPSERVER'
		Path = 'E:\DROP' 
		FullAccess = 'EDW_Supply'
		ChangeAccess = @('EDW_Ops', 'EDW_Admins')
		ReadAccess = '' 
	},
	@{ 
		Name = 'FTPDROP'  
		Path = 'E:\FTPDROP'
		FullAccess = ''
		ChangeAccess = 'Everyone'
		ReadAccess = ''
	}
)
```

**Comment by johlju** [comment]
To me that means that for example if `ChangeAccess = @('EDW_Ops', 'EDW_Admins')` and that configuration is changed to `ChangeAccess = @()` or `ChangeAccess = ''` that means that the previous permissions should be removed. Or if `ChangeAccess = @()` is set in the configuration and a user manually adds permissions, those will be removed.
I think one should not add parameters in a configuration that you don't want to keep in a desired state.

**Comment by bentcode** [comment]
I came here with this same issue and looking for this exact feature.
