### ISSUE TITLE
Permission change doesn't take effect

### ISSUE THREAD

**Issue by ghost** [PowerShell/xSmbShare#25]
Hi

I have created a share with xSmbShare and in NOAcces had "users"

Recently wanted to change Noaccess to "" and move "users" to ReadAccess, and allthough the Verbose runs says that the Set script i running, the share maintanes Noaccess for users, and completly ignores the newly added Read access

Seems like the script is trying to modify access, but it doesn't take effect.

PSVersion 5.1
xSmbShare 2.0.0
Server 2012 R2

**Comment by johlju** [comment]
Could you please provide your configuration and verbose output? Obfuscate any sensitive information.

**Comment by ghost** [comment]
Hey,
The new config should be this.

```
xSmbShare WWWRootShare
        {

          Ensure = 'Present'
          Name   = "WWWRoot"
          Path = "c:\inetpub\wwwroot" 
          Description = "Share til WWWroot"
          FullAccess = "BUILTIN\Administrators", "NT AUTHORITY\SYSTEM"
          ReadAccess = "BUILTIN\Users" #skal slås fra når GDPR er klar
          # NoAccess = "BUILTIN\Users" Skal slås til når GDPR er klar
          DependsOn = "[WindowsFeature]WebCommonHTTP"                   
        }
```
Old setting was

```
xSmbShare WWWRootShare
        {

          Ensure = 'Present'
          Name   = "WWWRoot"
          Path = "c:\inetpub\wwwroot" 
          Description = "Share til WWWroot"
          FullAccess = "BUILTIN\Administrators", "NT AUTHORITY\SYSTEM"          
          NoAccess = "BUILTIN\Users" 
          DependsOn = "[WindowsFeature]WebCommonHTTP"                   
        }
```
Unfortunatly i cant get the VERBOSE anymore as my servicewindow to the server has ended.

But it rans the SET script and wrote messages like:
setting rights FULL to "BUILTIN\Administrators", "NT AUTHORITY\SYSTEM"
Setting rights READ to "BUILTIN\Users"

**Comment by johlju** [comment]
Thanks for the old and new configuration! Helps a lot! I labeled this as help wanted so that someone in the community can run with this.

**Comment by johlju** [comment]
To remove the permission I think we need to use an empty collection. Although not sure it works. I will look into this issue when the resource is moved to ComputerManagementDsc.
 
```
xSmbShare WWWRootShare
{
    Ensure = 'Present'
    Name   = "WWWRoot"
    Path = "c:\inetpub\wwwroot" 
    Description = "Share til WWWroot"
    FullAccess = "BUILTIN\Administrators", "NT AUTHORITY\SYSTEM"          
    NoAccess = "BUILTIN\Users" 
    ReadAccess = @()
}
```

**Comment by johlju** [comment]
This will be resolved in PR https://github.com/PowerShell/ComputerManagementDsc/pull/211 and fixed in the resource that is moved to the ComputerManagementDsc module.

Closing this issue at this time.
