### ISSUE TITLE
Feature Request: Support Platforms where Get-SmbShare is Not Present

### ISSUE THREAD

**Issue by aolszowka** [PowerShell/xSmbShare#9]
I've started exploring Powershell DSC and I'm now starting to run into limitations with several of the pack-in and external Resources.

This Resource (xSmbShare) does not appear to work in platforms where Get-SmbShare and its kin are not present, it also does not fail gracefully, instead attempting to continue on despite the inability to do so. One such platform is Windows Server 2008R2

Unfortunately our farm requires us to support Windows Server 2008 R2 for the near future (2012 R2 is on the board for our next Technology Platform).

While not as pretty as Get-SmbShare and its kin, the Resource could be refactored to support the older "NET" wrapper which would give you capability within all Windows Server Platforms Powershell DSC currently targets, this would be my route should I hear nothing back.

I'd assume I could probably work around this by doing some remapping of Get-SmbShare and its kin in the Powershell Environment that is in use (obviously being careful to mimic the existing API), anyone attempting to use this Resource in a Linux environment would probably have to travel the same road...

**Comment by rodolfosalgado** [comment]
No progress on this ?

**Comment by johlju** [comment]
This resource is being moved to ComputerManagementDsc and this module will be deprecated, also the Windows Server 2008 R2 is closing in on its end support. This issue may be reopened in ComputerManagementDsc once it has been moved, if it still am issue at that time.

If someone want to work on this, then please do, and I can review up until the module have been deprecated.

I'm closing this issue at this time. Please comment on this issue if you want to work on this and I will reopen.

**Comment by aolszowka** [comment]
Thanks for at least following up with a WONTFIX that is helpful.
